site_name: Meu Projeto Youtube

theme:
  name: material

markdown_extensions:
  - pymdownx.mark # Relacionada ao realce
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
